### ISSUE TITLE
Storm UI not working in Firefox

### ISSUE THREAD

**Issue by opiechow** [smart-storm/storm-ui#12]
Attaching screenshot:

![obraz](https://user-images.githubusercontent.com/12622836/34461773-101291fe-ee34-11e7-964f-d267ba84986c.png)

Firefox version: 57.0.3 (64 bit)
OS Name: Microsoft Windows 10 Education
OS Version: 10.0.15063 N/A Build 15063

**Comment by VashingMachine** [comment]
Fixed

**Comment by jwszolek** [comment]
Closing issue.
